services:
  - type: web
    name: ai-assistant
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
    plan: free
    autoDeploy: true
